version: "3"
services:
  carteira_database:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - carteira_database.env

  carteira_app:
    image: aula/carteira-api
    expose:
      - 8082
    ports:
      - 8082:8082
    depends_on:
      - carteira_database
    env_file:
      - carteira_app.env
  