server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: AMam@!12
    url: jdbc:postgresql://localhost:5433/carteira_test
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
